[package]
name = "tetris-rs"
version = "0.1.0"
authors = ["blackbracken <me@bracken.black>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncurses = "5.100.0"
