[tasks.run]
command = "cargo"
args = ["run", "--package", "tetris-rs", "--bin", "tetris-rs"]
dependencies = ["copy_resources", "build"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.fix]
install_crate = false
command = "cargo"
args = ["+nightly", "fix", "--lib", "--allow-dirty"]

[tasks.before]
dependencies = ["format", "clippy", "test"]

[tasks.format]
install_crate = { crate_name = "rustfmt-nightly", rustup_component_name = "rustfmt-preview", binary = "rustfmt" }
command = "cargo"
args = ["+nightly", "fmt", "--all", "--", "--emit=files"]

[tasks.clippy]
install_crate = { crate_name = "clippy-nightly", rustup_component_name = "clippy-preview" }
command = "cargo"
args = ["+nightly", "clippy"]

[tasks.test]
command = "cargo"
args = ["test", "--all-features"]

[tasks.docs]
command = "cargo"
args = ["docs", "--no-deps", "--document-private-items", "--workspace", "--open"]

[tasks.copy_resources]
windows_alias = "windows_copy_resources"

[tasks.windows_copy_resources]
command = "xcopy"
args = ["resources", "target\\debug\\resources", "/S", "/I", "/Y"]
